INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1001"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1001
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1002"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1002
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1003"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1003
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1004"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1004
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1005"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1005
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1006"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1006
     SORT BY ts;

INSERT OVERWRITE LOCAL DIRECTORY "/home/buaa/output/1007"
     ROW FORMAT DELIMITED FIELDS TERMINATED by ',' 
     SELECT * FROM node_facts_1007
     SORT BY ts;